package model

import (
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// Venta is an atomic sale transaction tied to an open cash session.
// Estado: "completada" | "anulada"
type Venta struct {
	ID             uuid.UUID       `gorm:"type:uuid;primaryKey;default:gen_random_uuid()"`
	NumeroTicket   int             `gorm:"uniqueIndex;not null;autoIncrement"`
	SesionCajaID   uuid.UUID       `gorm:"type:uuid;index;not null"`
	UsuarioID      uuid.UUID       `gorm:"type:uuid;not null"`
	Subtotal       decimal.Decimal `gorm:"type:decimal(12,2);not null"`
	DescuentoTotal decimal.Decimal `gorm:"type:decimal(12,2);not null;default:0"`
	Total          decimal.Decimal `gorm:"type:decimal(12,2);not null"`
	Estado         string          `gorm:"type:varchar(20);not null;default:'completada'"`
	ComprobanteID  *uuid.UUID      `gorm:"type:uuid"`
	// OfflineID stores the local UUID generated by the PWA when offline
	OfflineID      *string `gorm:"type:varchar(36);index"`
	ConflictoStock bool    `gorm:"not null;default:false"`
	CreatedAt      time.Time

	Usuario *Usuario  `gorm:"foreignKey:UsuarioID"`
	Items   []VentaItem `gorm:"foreignKey:VentaID"`
	Pagos   []VentaPago `gorm:"foreignKey:VentaID"`
}

func (Venta) TableName() string { return "ventas" }

// VentaItem is one line of a sale. Price is captured at sale time.
type VentaItem struct {
	ID             uuid.UUID       `gorm:"type:uuid;primaryKey;default:gen_random_uuid()"`
	VentaID        uuid.UUID       `gorm:"type:uuid;not null;index"`
	ProductoID     uuid.UUID       `gorm:"type:uuid;not null"`
	Cantidad       int             `gorm:"not null"`
	PrecioUnitario decimal.Decimal `gorm:"type:decimal(10,2);not null"`
	DescuentoItem  decimal.Decimal `gorm:"type:decimal(10,2);not null;default:0"`
	Subtotal       decimal.Decimal `gorm:"type:decimal(12,2);not null"`

	Producto *Producto `gorm:"foreignKey:ProductoID"`
}

func (VentaItem) TableName() string { return "venta_items" }

// VentaPago records one payment method applied to a sale.
// Metodo: "efectivo" | "debito" | "credito" | "transferencia"
type VentaPago struct {
	ID      uuid.UUID       `gorm:"type:uuid;primaryKey;default:gen_random_uuid()"`
	VentaID uuid.UUID       `gorm:"type:uuid;not null;index"`
	Metodo  string          `gorm:"type:varchar(20);not null"`
	Monto   decimal.Decimal `gorm:"type:decimal(12,2);not null"`
}

func (VentaPago) TableName() string { return "venta_pagos" }
