// BlendPOS API
//
//	@title                      BlendPOS API
//	@version                    1.0
//	@description                Backend REST API para BlendPOS — punto de venta con soporte offline, facturación AFIP y gestión de inventario.
//	@termsOfService             https://blendpos.ar/terms
//	@contact.name               Soporte BlendPOS
//	@contact.email              soporte@blendpos.ar
//	@license.name               Private
//	@host                       localhost:8000
//	@BasePath                   /
//	@schemes                    http https
//	@securityDefinitions.apikey BearerAuth
//	@in                         header
//	@name                       Authorization
//	@description                Ingrese el token JWT con el prefijo "Bearer": Bearer <token>
package main

import (
	"context"
	"fmt"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	_ "blendpos/docs" // generated by swag init
	"blendpos/internal/config"
	"blendpos/internal/infra"
	"blendpos/internal/repository"
	"blendpos/internal/router"
	"blendpos/internal/service"
	"blendpos/internal/worker"

	"github.com/rs/zerolog"
	"github.com/rs/zerolog/log"
)

func main() {
	// ── H-03: Configure logger based on environment ─────────────────────
	// Preliminary console logger until config is loaded.
	log.Logger = log.Output(zerolog.ConsoleWriter{Out: os.Stderr, TimeFormat: time.RFC3339})

	cfg, err := config.Load()
	if err != nil {
		log.Fatal().Err(err).Msg("failed to load config")
	}

	// Now reconfigure the global logger according to APP_ENV.
	if cfg.Env == "development" {
		zerolog.SetGlobalLevel(zerolog.DebugLevel)
		log.Logger = zerolog.New(zerolog.ConsoleWriter{
			Out:        os.Stderr,
			TimeFormat: time.Kitchen,
		}).With().Timestamp().Caller().Logger()
	} else {
		zerolog.SetGlobalLevel(zerolog.InfoLevel)
		log.Logger = zerolog.New(os.Stderr).
			With().
			Timestamp().
			Str("service", "blendpos-backend").
			Str("env", cfg.Env).
			Logger()
	}

	db, err := infra.NewDatabase(cfg.DatabaseURL)
	if err != nil {
		log.Fatal().Err(err).Msg("failed to connect to postgres")
	}

	rdb, err := infra.NewRedis(cfg.RedisURL)
	if err != nil {
		log.Fatal().Err(err).Msg("failed to connect to redis")
	}

	// ── Circuit Breaker for AFIP Sidecar ─────────────────────────────────────
	afipCB := infra.NewCircuitBreaker(infra.DefaultCBConfig())

	// Start goroutine worker pool for async tasks (invoicing, email, PDF).
	// Worker handlers are wired here (composition root) so that the pool
	// has full access to all infrastructure dependencies (RF-17, RF-19, RF-21).
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	afipClient := infra.NewAFIPClient(cfg.AFIPSidecarURL, cfg.InternalAPIToken)
	mailer := infra.NewMailer(cfg)
	dispatcher := worker.NewDispatcher(rdb, afipClient, mailer)

	// ── Repositories (single instances, shared by workers + HTTP handlers) ──
	comprobanteRepo := repository.NewComprobanteRepository(db)
	ventaRepo := repository.NewVentaRepository(db)
	usuarioRepo := repository.NewUsuarioRepository(db)
	productoRepo := repository.NewProductoRepository(db)
	cajaRepo := repository.NewCajaRepository(db)
	proveedorRepo := repository.NewProveedorRepository(db)
	historialPrecioRepo := repository.NewHistorialPrecioRepository(db)
	movimientoStockRepo := repository.NewMovimientoStockRepository(db)
	categoriaRepo := repository.NewCategoriaRepository(db)
	auditRepo := repository.NewAuditRepository(db)
	compraRepo := repository.NewCompraRepository(db)
	promocionRepo := repository.NewPromocionRepository(db)
	configFiscalRepo := repository.NewConfiguracionFiscalRepository(db)

	// ── Services ─────────────────────────────────────────────────────────────
	authSvc := service.NewAuthService(usuarioRepo, cfg, rdb)
	productoSvc := service.NewProductoService(productoRepo, movimientoStockRepo, categoriaRepo, rdb)
	inventarioSvc := service.NewInventarioService(productoRepo, movimientoStockRepo)
	cajaSvc := service.NewCajaService(cajaRepo)
	ventaSvc := service.NewVentaService(ventaRepo, inventarioSvc, cajaSvc, cajaRepo, productoRepo, dispatcher, comprobanteRepo, configFiscalRepo)
	facturacionSvc := service.NewFacturacionService(comprobanteRepo, dispatcher)
	proveedorSvc := service.NewProveedorService(proveedorRepo, productoRepo)
	categoriaSvc := service.NewCategoriaService(categoriaRepo)
	auditSvc := service.NewAuditService(auditRepo)
	compraSvc := service.NewCompraService(compraRepo)
	promocionSvc := service.NewPromocionService(promocionRepo)
	configFiscalSvc := service.NewConfiguracionFiscalService(configFiscalRepo, afipClient)

	workerHandlers := &worker.WorkerHandlers{
		Facturacion: worker.NewFacturacionWorker(afipClient, afipCB, comprobanteRepo, ventaRepo, dispatcher, cfg.PDFStoragePath, configFiscalSvc),
		Email:       worker.NewEmailWorker(mailer),
	}

	// Separated worker pools: facturacion and email don't starve each other
	facWorkers := cfg.FacturacionWorkers
	if facWorkers <= 0 {
		facWorkers = cfg.WorkerPoolSize
	}
	emailWorkers := cfg.EmailWorkers
	if emailWorkers <= 0 {
		emailWorkers = cfg.WorkerPoolSize
	}
	workerPool := worker.StartWorkerPool(ctx, rdb, workerHandlers, worker.WorkerPoolConfig{
		FacturacionWorkers: facWorkers,
		EmailWorkers:       emailWorkers,
	})

	// Retry cron for pending AFIP comprobantes
	worker.StartRetryCron(ctx, worker.RetryCronConfig{
		ComprobanteRepo: comprobanteRepo,
		AFIPClient:      afipClient,
		CB:              afipCB,
		RDB:             rdb,
		ConfigFiscalSvc: configFiscalSvc,
	})

	r := router.New(router.Deps{
		Cfg:                 cfg,
		DB:                  db,
		RDB:                 rdb,
		AfipCB:              afipCB,
		AuthSvc:             authSvc,
		ProductoSvc:         productoSvc,
		InventarioSvc:       inventarioSvc,
		VentaSvc:            ventaSvc,
		CajaSvc:             cajaSvc,
		FacturacionSvc:      facturacionSvc,
		ConfigFiscalSvc:     configFiscalSvc,
		ProveedorSvc:        proveedorSvc,
		CategoriaSvc:        categoriaSvc,
		AuditSvc:            auditSvc,
		CompraSvc:           compraSvc,
		PromocionSvc:        promocionSvc,
		ProductoRepo:        productoRepo,
		HistorialPrecioRepo: historialPrecioRepo,
		AuditRepo:           auditRepo,
		ComprobanteRepo:     comprobanteRepo,
		VentaRepo:           ventaRepo,
		Dispatcher:          dispatcher,
	})

	srv := &http.Server{
		Addr:         fmt.Sprintf(":%d", cfg.Port),
		Handler:      r,
		ReadTimeout:  10 * time.Second,
		WriteTimeout: 30 * time.Second,
		IdleTimeout:  60 * time.Second,
	}

	// Graceful shutdown on SIGINT / SIGTERM
	go func() {
		log.Info().Msgf("BlendPOS backend listening on :%d", cfg.Port)
		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			log.Fatal().Err(err).Msg("server error")
		}
	}()

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit

	log.Info().Msg("shutting down — draining workers…")

	// 1. Cancel worker context so they stop picking up new jobs.
	cancel()

	// 2. Wait for in-flight jobs to finish (max 30s).
	workerDone := make(chan struct{})
	go func() {
		workerPool.Wait()
		close(workerDone)
	}()

	select {
	case <-workerDone:
		log.Info().Msg("all workers finished gracefully")
	case <-time.After(30 * time.Second):
		log.Warn().Msg("timeout waiting for workers — forcing shutdown")
	}

	// 3. Shutdown HTTP server.
	shutdownCtx, shutdownCancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer shutdownCancel()
	if err := srv.Shutdown(shutdownCtx); err != nil {
		log.Fatal().Err(err).Msg("forced shutdown")
	}

	// 4. Close infrastructure connections.
	sqlDB, _ := db.DB()
	if sqlDB != nil {
		_ = sqlDB.Close()
	}
	_ = rdb.Close()

	log.Info().Msg("server exited")
}
